server:
  port: 8888

spring:
  application:
    name: loja

  cloud:
    config:
      server:
        git:
          uri: https://github.com/italo-kelmy/ConfiguracaoSpringCloudConfig
          default-label: master
          clone-on-start: true

